/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;



/**
 *
 * @author SahiL
 */

public class STR extends JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public static String rol="hello";
    public static String cla="hello";
    public static String name="hello";
    
    public static String engs1="hello";
    public static String ecos1="hello";
    public static String accs1="hello";
    public static String bsts1="hello";
    public static String mips1="hello";
    public static String phys1="hello";
    
    public static String engs2="hello";
    public static String ecos2="hello";
    public static String accs2="hello";
    public static String bsts2="hello";
    public static String mips2="hello";
    public static String phys2="hello";
    
    public static String engs3="hello";
    public static String ecos3="hello";
    public static String accs3="hello";
    public static String bsts3="hello";
    public static String mips3="hello";
    public static String phys3="hello";
    
    public static String stream="?";
    public static String grade="?";
    public static int percent=0;

    
    

    /**
     * Creates new form Student_Report_Card
     */
    public STR() {
        initComponents();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Streambtngrp = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        msgLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        msgLabel1 = new javax.swing.JLabel();
        VersionBox = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dbframe = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        portal = new javax.swing.JFrame();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jOptionPane = new javax.swing.JOptionPane();
        calc = new javax.swing.JFrame();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jLabel43 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jDialog1.setTitle("Operation Successfull");
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setLocationByPlatform(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(379, 180));

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Return");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Save to Database");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        msgLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(95, 95, 95))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(msgLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        VersionBox.setTitle("Report Card");
        VersionBox.setLocationByPlatform(true);
        VersionBox.setMinimumSize(new java.awt.Dimension(180, 160));
        VersionBox.setResizable(false);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Version: 2.0");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Created by Group 9");

        javax.swing.GroupLayout VersionBoxLayout = new javax.swing.GroupLayout(VersionBox.getContentPane());
        VersionBox.getContentPane().setLayout(VersionBoxLayout);
        VersionBoxLayout.setHorizontalGroup(
            VersionBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VersionBoxLayout.createSequentialGroup()
                .addGroup(VersionBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VersionBoxLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel34))
                    .addGroup(VersionBoxLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel35)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        VersionBoxLayout.setVerticalGroup(
            VersionBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VersionBoxLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        dbframe.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dbframe.setTitle("Student Data Records");
        dbframe.setBackground(new java.awt.Color(255, 255, 255));
        dbframe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dbframe.setForeground(new java.awt.Color(255, 255, 255));
        dbframe.setLocationByPlatform(true);
        dbframe.setMinimumSize(new java.awt.Dimension(645, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Name", "Class", "Stream", "Total Marks", "Grade", "Percentage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton8.setText("Return back to the Portal");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Delete Selected Record");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton13.setText("Update Selected Record");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbframeLayout = new javax.swing.GroupLayout(dbframe.getContentPane());
        dbframe.getContentPane().setLayout(dbframeLayout);
        dbframeLayout.setHorizontalGroup(
            dbframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(dbframeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton10)
                .addGap(46, 46, 46)
                .addComponent(jButton13)
                .addGap(47, 47, 47)
                .addComponent(jButton8))
        );
        dbframeLayout.setVerticalGroup(
            dbframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbframeLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(dbframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jButton13)
                    .addComponent(jButton8)))
        );

        portal.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        portal.setTitle("Portal Page");
        portal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        portal.setLocationByPlatform(true);
        portal.setMinimumSize(new java.awt.Dimension(476, 373));
        portal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("VIEW RESULTS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        portal.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText(" RESULT CALCULATOR");
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        portal.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("LOGOUT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        portal.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 90, 25));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("CONTACT US");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        portal.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 110, -1));

        jLabel46.setBackground(new java.awt.Color(102, 102, 102));
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel46.setOpaque(true);
        portal.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 264, 480, 80));
        portal.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 460, 10));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/smart_class.png"))); // NOI18N
        portal.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, 490, 410));

        calc.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        calc.setTitle("Results Calculator Page");
        calc.setBackground(new java.awt.Color(153, 0, 153));
        calc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calc.setForeground(new java.awt.Color(153, 255, 51));
        calc.setLocationByPlatform(true);
        calc.setMinimumSize(new java.awt.Dimension(857, 740));
        calc.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        calc.getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 77, -1));

        jLabel20.setText("Business Studies");
        calc.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, 20));
        calc.getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 77, -1));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 77, -1));

        jLabel22.setText("Physical Education");
        calc.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, -1, -1));
        calc.getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 77, -1));

        jLabel21.setText("Maths/IP/Hindi");
        calc.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, 10));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 204));
        jLabel23.setText("REPORT CARD");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 51, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Student Name:-                    \nClass:-\nRoll No:-\n--------------------------------------\nTotal Marks(SA1):-\nTotal Marks(SA2):-\nTotal Marks(SA3):-\nFinal Total Marks:-\nGrade:-\nPercentage:-\n--------------------------------------");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(51, 0, 51));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("REMARKS");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Something Public School");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/star.png"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/star.png"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/report.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel29)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel32)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel28)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        calc.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 11, -1, -1));
        calc.getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 77, -1));
        calc.getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 77, -1));
        calc.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 77, -1));

        jLabel13.setText("Business Studies");
        calc.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel14.setText("Maths/IP/Hindi");
        calc.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel15.setText("Physical Education");
        calc.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));
        calc.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 77, -1));
        calc.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 77, -1));
        calc.getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 77, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Summative Assesment III (SA3)");
        calc.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Summative Assesment I (SA1)");
        calc.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 194, -1, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Student Report Calculator");
        calc.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, -1, -1));

        jLabel6.setText("Business Studies");
        calc.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 214, -1, 30));

        jLabel17.setText("English");
        calc.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel5.setText("Accounts");
        calc.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel4.setText("Economics");
        calc.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 264, -1, 20));

        jLabel19.setText("Accounts");
        calc.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel3.setText("English");
        calc.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel18.setText("Economics");
        calc.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel8.setText("Physical Education");
        calc.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel7.setText("Maths/IP/Hindi");
        calc.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 264, -1, 10));
        calc.getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 123, -1));

        jLabel27.setText("Roll No:");
        calc.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 50, -1));
        calc.getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 123, -1));

        jLabel12.setText("Accounts");
        calc.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel26.setText("Class:");
        calc.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 123, -1));

        jLabel10.setText("English");
        calc.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel11.setText("Economics");
        calc.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        calc.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 77, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Summative Assesment II (SA2)");
        calc.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));
        calc.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 77, -1));
        calc.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 77, -1));
        calc.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 77, -1));
        calc.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 77, -1));
        calc.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 77, -1));
        calc.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 77, -1));

        jLabel31.setText("Choose Stream:");
        calc.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        Streambtngrp.add(jRadioButton1);
        jRadioButton1.setText("Commerce");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 20));

        Streambtngrp.add(jRadioButton2);
        jRadioButton2.setText("Humanities");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Compute Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 170, 80));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 160, 80));
        calc.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 77, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Student Details");
        calc.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel25.setText("Name:");
        calc.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jButton9.setText("Return back to the Portal");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        calc.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 638, -1, -1));

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("View Portal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("View Database");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Visit our Website");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Version");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        calc.setJMenuBar(jMenuBar1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setBounds(getBounds());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(getBounds());
        setMinimumSize(getPreferredSize());
        setName("jFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Trajan Pro", 0, 23)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 204));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/srm1.png"))); // NOI18N
        jLabel43.setLabelFor(this);
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 450, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 102));
        jLabel38.setText("NEWS: Server is online and fully functional, if you are experiencing any issues contact us via our helpdesk.");
        jLabel38.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel41.setBackground(new java.awt.Color(204, 204, 255));
        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 51, 51));
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.setOpaque(true);
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, 746, 110));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/background.jpg"))); // NOI18N
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("PASSWORD:");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 130, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("USERNAME:");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 92, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 127, 127, -1));

        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 165, 82, -1));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 89, 127, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 102, 102));
        jLabel44.setText("Login below for authentication");
        jLabel44.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 450, 10));

        getAccessibleContext().setAccessibleName("jFrame");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()==true) {
        stream="com";
        }
        if(jRadioButton2.isSelected()==true) {
        stream="hum";
        }
        
        
        name = jTextField19.getText();
         cla = jTextField20.getText();                  //  Getting Student Details...  
         rol = jTextField21.getText();

        engs1 = jTextField1.getText();
        ecos1 = jTextField2.getText();
        accs1 = jTextField3.getText();     //  Getting SA1 Marks...
        bsts1 = jTextField4.getText();
        mips1 = jTextField5.getText();
        phys1 = jTextField6.getText();

        engs2 = jTextField7.getText();
        ecos2 = jTextField8.getText();
        accs2 = jTextField9.getText();     //  Getting SA2 Marks...
        bsts2 = jTextField10.getText();
        mips2 = jTextField11.getText();
        phys2 = jTextField12.getText();
        
        engs3 = jTextField13.getText();
        ecos3 = jTextField14.getText();
        accs3 = jTextField15.getText();     //  Getting SA3 Marks...
        bsts3 = jTextField16.getText();
        mips3 = jTextField17.getText();
        phys3 = jTextField18.getText();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields"); 
        } else if (cla.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } else if (rol.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (engs1.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");             
        } else if (ecos1.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");            
        } else if (accs1.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (bsts1.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");             
        } else if (mips1.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (phys1.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (engs2.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");             
        } else if (ecos2.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (accs2.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } else if (bsts2.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } else if (mips2.isEmpty()) {           
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");             
        } else if (phys2.isEmpty()) {         
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (engs3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (ecos3.isEmpty()) {            
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");          
        } else if (accs3.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");               
        } else if (bsts3.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } else if (mips3.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } else if (phys3.isEmpty()) {             
            JOptionPane.showMessageDialog(null, "ERROR: Please fill all the fields");              
        } 
        
        else {
            jButton5.setVisible(true);
            msgLabel.setText("Report card generated successfully");
            msgLabel.setForeground(Color.GREEN);
            jDialog1.setTitle("GENERATED");
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);


            int eng1 = Integer.parseInt(jTextField1.getText());
            int eco1 = Integer.parseInt(jTextField2.getText());
            int acc1 = Integer.parseInt(jTextField3.getText());     //  Getting SA1 Marks...
            int bst1 = Integer.parseInt(jTextField4.getText());
            int mip1 = Integer.parseInt(jTextField5.getText());
            int phy1 = Integer.parseInt(jTextField6.getText());

            int eng2 = Integer.parseInt(jTextField7.getText());
            int eco2 = Integer.parseInt(jTextField8.getText());
            int acc2 = Integer.parseInt(jTextField9.getText());      //  Getting SA2 Marks...
            int bst2 = Integer.parseInt(jTextField10.getText());
            int mip2 = Integer.parseInt(jTextField11.getText());
            int phy2 = Integer.parseInt(jTextField12.getText());

            int eng3 = Integer.parseInt(jTextField13.getText());
            int eco3 = Integer.parseInt(jTextField14.getText());
            int acc3 = Integer.parseInt(jTextField15.getText());     //  Getting SA3 Marks...
            int bst3 = Integer.parseInt(jTextField16.getText());
            int mip3 = Integer.parseInt(jTextField17.getText());
            int phy3 = Integer.parseInt(jTextField18.getText());

            int total1 = eng1 + eco1 + acc1 + bst1 + mip1;
            int total2 = eng2 + eco2 + acc2 + bst2 + mip2;       //  Adding Marks...
            int total3 = eng3 + eco3 + acc3 + bst3 + mip3;

            int per1 = total1 * 20 / 100;
            int per2 = total2 * 20 / 100;            //  Taking out percentages cut out of added marks...
            int per3 = total3 * 60 / 100;

            int totalf = per1 + per2 + per3;        //  Adding 20%,20%,60% taken out from all summatives i.e. final marks...
            int percent = totalf * 100 / 500;       //  Taking out Final Percentage...

            grade = "?";
            if (percent < 30) {
                grade = "E";
            }
            if (percent >= 30) {
                grade = "D";
            }
            if (percent >= 45) {
                grade = "C";        //  Assigning Grades according to percentage...
            }
            if (percent >= 60) {
                grade = "B";
            }
            if (percent >= 80) {
                grade = "A";
            }

            if (grade.equals("E")) {
                jTextArea2.setText("Failed, sorry but you will not" + "\n"
                        + "be promoted to next class,"
                        + "\n" + "so you will need to redo" + "\n" + "the class once again.");
                jTextArea2.setForeground(Color.red);
            }
            if (grade.equals("D")) {
                jTextArea2.setText("Passed, but you need to improve" + "\n" + //  Giving Remarks according to grades...
                        "alot, else it will be too late.");
                jTextArea2.setForeground(Color.green);
            }
            if (grade.equals("C")) {
                jTextArea2.setText("Passed with good marks, "
                        + "\n" + "good luck for your future.");
                jTextArea2.setForeground(Color.green);
            }
            if (grade.equals("B")) {
                jTextArea2.setText("Passed with excellence, keep it up.");
                jTextArea2.setForeground(Color.green);
            }
            if (grade.equals("A")) {
                jTextArea2.setText("Outstanding, you have a very"
                        + "\n" + "bright future, best of luck.");
                jTextArea2.setForeground(Color.magenta);
            }


            jTextArea1.setText("Student Name:- " + name + "\n" + "Class:- " + cla + "\n" + "Roll No:- " + rol + "\n"
                    + "--------------------------------------" + "\n" + "Total Marks(SA1):- " + total1 + //  Making Report Card...
                    "\n" + "Total Marks(SA2):- " + total2 + "\n" + "Total Marks(SA3):- " + total3 + "\n"
                    + "Final Total Marks:- " + totalf + "\n" + "Grade:- " + grade + "\n" + "Percentage:- " + percent + "\n"
                    + "--------------------------------------");

        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("English");
        jLabel4.setText("Economics");
        jLabel5.setText("Accounts");                      //  Changing SA1 Subjects to Commerce...
        jLabel6.setText("Business Studies");
        jLabel7.setText("Maths/IP/Hindi");

        jLabel10.setText("English");
        jLabel11.setText("Economics");
        jLabel12.setText("Accounts");                     //  Changing SA2 Subjects to Commerce...
        jLabel13.setText("Business Studies");
        jLabel14.setText("Maths/IP/Hindi");

        jLabel17.setText("English");
        jLabel18.setText("Economics");
        jLabel19.setText("Accounts");                     //  Changing SA3 Subjects to Commerce...
        jLabel20.setText("Business Studies");
        jLabel21.setText("Maths/IP/Hindi");
        if (jRadioButton1.isSelected() == true) {
            jRadioButton1.setText("<html><b>Commerce</b></html>");
        }
        if (jRadioButton2.isSelected() == false) {
            jRadioButton2.setText("Humanities");
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("English");
        jLabel4.setText("Geography");
        jLabel5.setText("Economics");                       //  Changing SA1 Subjects to Humanities...
        jLabel6.setText("Political Science");
        jLabel7.setText("Maths/IP/Hindi");

        jLabel10.setText("English");
        jLabel11.setText("Geography");
        jLabel12.setText("Economics");                      //  Changing SA2 Subjects to Humanities...
        jLabel13.setText("Political Science");
        jLabel14.setText("Maths/IP/Hindi");
        
        jLabel17.setText("English");
        jLabel18.setText("Geography");
        jLabel19.setText("Economics");                      //  Changing SA3 Subjects to Humanities...
        jLabel20.setText("Political Science");
        jLabel21.setText("Maths/IP/Hindi");

        if (jRadioButton2.isSelected() == true) {
            jRadioButton2.setText("<html><b>Humanities</b></html>");
        }
        if (jRadioButton1.isSelected() == false) {
            jRadioButton1.setText("Commerce");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");             //  Clearing SA1 Marks...
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");

        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");              //  Clearing SA2 Marks...
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");

        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");             //  Clearing SA3 Marks...
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");

        jTextField19.setText("");
        jTextField20.setText("");             //  Clearing Student Details...
        jTextField21.setText("");

        jTextArea1.setText("Student Name:- " + "\n" + "Class:- " + "\n" + "Roll No:- " + "\n"
                + "--------------------------------------" + "\n" + "Total Marks(SA1):- " + //  Clearing Report Card...
                "\n" + "Total Marks(SA2):- " + "\n" + "Total Marks(SA3):- " + "\n"
                + "Final Total Marks:- " + "\n" + "Grade:- " + "\n" + "Percentage:- " + "\n"
                + "--------------------------------------");

        jTextArea2.setText("");                //  Clearing Remarks...

        JOptionPane.showMessageDialog(null,"Removed data from all the fields!");
        
        //msgLabel.setText("Removed data from all the fields!");
        //jDialog1.setTitle("Operation completed successfully");
        //msgLabel.setForeground(Color.blue);
        //jDialog1.setVisible(true);
        //jButton5.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String usr = jTextField22.getText();
        String pwd = new String(jPasswordField1.getPassword());
        String pass = "kebab";
        String user = "admin";
        if (pwd.isEmpty() || usr.isEmpty()) {
            JOptionPane.showMessageDialog(null,"ERROR: Please fill in both Username and Password!");
        } 
        else if (pwd.equals(pass) && usr.equals(user)) {
            boolean access=true;
            this.dispose();
            JOptionPane.showMessageDialog(null, "You have logged in successfully.");
            portal.setLocationRelativeTo(null);
            portal.setVisible(true);           
        } 
        else {
            JOptionPane.showMessageDialog(null,"ERROR: Invalid Username or Password!");
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String name = jTextField19.getText();
        String cla = jTextField20.getText();                  //  Getting Student Details...  
        int rol = Integer.parseInt(jTextField21.getText());
        String stm=null;
        if (jRadioButton1.isSelected()) {
            stm="Commerce";
        }
        else if (jRadioButton2.isSelected()) {
            stm="Humanities";
        }
            int eng1 = Integer.parseInt(jTextField1.getText());
            int eco1 = Integer.parseInt(jTextField2.getText());
            int acc1 = Integer.parseInt(jTextField3.getText());     //  Getting SA1 Marks...
            int bst1 = Integer.parseInt(jTextField4.getText());
            int mip1 = Integer.parseInt(jTextField5.getText());
            int phy1 = Integer.parseInt(jTextField6.getText());

            int eng2 = Integer.parseInt(jTextField7.getText());
            int eco2 = Integer.parseInt(jTextField8.getText());
            int acc2 = Integer.parseInt(jTextField9.getText());      //  Getting SA2 Marks...
            int bst2 = Integer.parseInt(jTextField10.getText());
            int mip2 = Integer.parseInt(jTextField11.getText());
            int phy2 = Integer.parseInt(jTextField12.getText());

            int eng3 = Integer.parseInt(jTextField13.getText());
            int eco3 = Integer.parseInt(jTextField14.getText());
            int acc3 = Integer.parseInt(jTextField15.getText());     //  Getting SA3 Marks...
            int bst3 = Integer.parseInt(jTextField16.getText());
            int mip3 = Integer.parseInt(jTextField17.getText());
            int phy3 = Integer.parseInt(jTextField18.getText());

            int total1 = eng1 + eco1 + acc1 + bst1 + mip1;
            int total2 = eng2 + eco2 + acc2 + bst2 + mip2;       //  Adding Marks...
            int total3 = eng3 + eco3 + acc3 + bst3 + mip3;

            int per1 = total1 * 20 / 100;
            int per2 = total2 * 20 / 100;            //  Taking out percentages cut out of added marks...
            int per3 = total3 * 60 / 100;

            int totalf = per1 + per2 + per3;        //  Adding 20%,20%,60% taken out from all summatives i.e. final marks...
            percent = totalf * 100 / 500;       //  Taking out Final Percentage...

            String grade = "?";
            if (percent < 30) {
                grade = "E";
            }
            if (percent >= 30) {
                grade = "D";
            }
            if (percent >= 45) {
                grade = "C";        //  Assigning Grades according to percentage...
            }
            if (percent >= 60) {
                grade = "B";
            }
            if (percent >= 80) {
                grade = "A";
            }

        try {

            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost","root","root");
            stmt = conn.createStatement();                      
            String create = "CREATE DATABASE IF NOT EXISTS school;";
            stmt.executeUpdate(create);
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();          
            
            create = "CREATE TABLE IF NOT EXISTS student(rollno int(2),name char(30),class char(10),stream char(20),totalmarks int(5),grade char(2),percentage int(3), PRIMARY KEY (rollno,class));";
            stmt.executeUpdate(create);
            
            String insert = "INSERT INTO student VALUES("+rol+",'"+name+"','"+cla+"','"+stm+"',"+totalf+",'"+grade+"',"+percent+");";
            stmt.executeUpdate(insert);
            JOptionPane.showMessageDialog(null,"Saved to Database Successfully.");
            marksheet m = new marksheet();
            jDialog1.setVisible(false);
            m.setLocationRelativeTo(null);
            m.setVisible(true);          
            //msgLabel1.setText("Saved to Database Successfully");
            //msgLabel1.setForeground(Color.blue);
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error in Connectivity - "+e);
        }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
             
            Class.forName("java.sql.Driver");
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost","root","root");
            stmt = conn.createStatement();                      
            String create = "CREATE DATABASE IF NOT EXISTS school;";
            stmt.executeUpdate(create);
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();
            String query = "Select * from student order by rollno;";
            rs = stmt.executeQuery(query);

            while(rs.next()) {
                int rn = rs.getInt(1);
                String name = rs.getString(2);
                String cla = rs.getString(3);
                String stream = rs.getString(4);
                int tm = rs.getInt(5);
                String grade = rs.getString(6);
                int percent = rs.getInt(7);   
                
                model.addRow(new Object[] {rn,name,cla,stream,tm,grade,percent});
            }           
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error in Connectivity - "+e);
        }
        
        calc.setVisible(false);
        dbframe.setLocationRelativeTo(null);
        dbframe.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        VersionBox.setLocationRelativeTo(null);
        VersionBox.setTitle("Version Information");
        VersionBox.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
             
            Class.forName("java.sql.Driver");
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost","root","root");
            stmt = conn.createStatement();                      
            String create = "CREATE DATABASE IF NOT EXISTS school;";
            stmt.executeUpdate(create);
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();
            String query = "Select * from student order by rollno;";
            rs = stmt.executeQuery(query);
            
            while(rs.next()) {
                int rn = rs.getInt(1);
                String name = rs.getString(2);
                String cla = rs.getString(3);
                String stream = rs.getString(4);
                int tm = rs.getInt(5);
                String grade = rs.getString(6);
                int percent = rs.getInt(7);   
                
                model.addRow(new Object[] {rn,name,cla,stream,tm,grade,percent});
            }           
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error in Connectivity - "+e);
        }
        portal.setVisible(false);
        dbframe.setLocationRelativeTo(null);
        dbframe.setVisible(true);        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        portal.setVisible(false);
        calc.setLocationRelativeTo(null);      
        calc.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        portal.setVisible(true);
        dbframe.setVisible(false);
        DefaultTableModel m=(DefaultTableModel) jTable1.getModel();
        m.getDataVector().removeAllElements();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        calc.setVisible(false);
        portal.setLocationRelativeTo(null);
        portal.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        calc.setVisible(false);
        portal.setLocationRelativeTo(null);
        portal.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
        Runtime r = Runtime.getRuntime();
        r.exec("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe http://www.website.com/");
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows=jTable1.getSelectedRow();
        if(rows==-1) 
                JOptionPane.showMessageDialog(null, "First, please select a row you want to delete!");
            else
                try {
             
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();           
            Object rn=jTable1.getValueAt(rows,0);
            String del = "Delete from student where rollno="+rn+";";
            stmt.executeUpdate(del);  
            JOptionPane.showMessageDialog(null, "Record has been deleted successfully.");
        }
        
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error in Connectivity - "+e);
        }
        
        
         int rowsc=model.getRowCount();
         if(rowsc>0) {
             for (int i=0;i<rowsc;i++) {
                 model.removeRow(0);
             }
         }
                 
         
         try {
             
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();
            String query = "Select * from student order by rollno;";
            rs = stmt.executeQuery(query);
            
            while(rs.next()) {
                int rn = rs.getInt(1);
                String name = rs.getString(2);
                String cla = rs.getString(3);
                String stream = rs.getString(4);
                int tm = rs.getInt(5);
                String grade = rs.getString(6);
                int percent = rs.getInt(7);   
                
                model.addRow(new Object[] {rn,name,cla,stream,tm,grade,percent});
            }           
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error in Connectivity - "+e);
        }
            
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        portal.setVisible(false);
        JOptionPane.showMessageDialog(null, "You have been logged out successfully.");
        new STR().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        calc.setVisible(false);
        JOptionPane.showMessageDialog(null, "You have been logged out successfully.");
        new STR().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "If you have any any issues concerned to our software please mail us to helpdesk@schoolsoft.com");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows=jTable1.getSelectedRow();
        if(rows>=0 && jTable1.isEditing()==false) {               
        try {
             
            Class.forName("java.sql.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/school","root","root");
            stmt = conn.createStatement();
            Object rn=jTable1.getValueAt(rows,0);
            Object nm=jTable1.getValueAt(rows,1);
            Object cla=jTable1.getValueAt(rows,2);
            Object strm=jTable1.getValueAt(rows,3);
            Object tm=jTable1.getValueAt(rows,4);
            Object gra=jTable1.getValueAt(rows,5);
            Object per=jTable1.getValueAt(rows,6);
            String update = "Update student set name='"+nm+"',class='"+cla+"',stream='"+strm+"',totalmarks="+tm+",grade='"+gra+"',percentage="+per+" where rollno="+rn+";";
            JOptionPane.showMessageDialog(null, "Record has been updated successfully.");
            stmt.executeUpdate(update);  
         
        }
                catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error - "+e);
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row and press enter after editing it!");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        //</editor-fold>

        //</editor-fold>

        /*
         * Create and display the form
         */
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new STR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Streambtngrp;
    private javax.swing.JDialog VersionBox;
    private javax.swing.JFrame calc;
    private javax.swing.JFrame dbframe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JLabel msgLabel1;
    private javax.swing.JFrame portal;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @author student
     */
    public static class Welcome extends JFrame {

        /**
         * Creates new form Welcome
         */
        public Welcome() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        @SuppressWarnings(value = "unchecked")
        private void initComponents() {
            jLabel3 = new JLabel();
            jLabel4 = new JLabel();
            jLabel1 = new JLabel();
            jLabel2 = new JLabel();
            jLabel5 = new JLabel();
            jButton1 = new JButton();
            jLabel3.setText("jLabel3");
            jLabel4.setText("jLabel4");
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            jLabel2.setIcon(new ImageIcon(getClass().getResource("/Project/resources/welcome page.gif"))); // NOI18N
            jLabel5.setBackground(new Color(51, 51, 255));
            jLabel5.setFont(new Font("Tahoma", 1, 48)); // NOI18N
            jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel5.setText("Welcome");
            jLabel5.setOpaque(true);
            jButton1.setText("PROCEED");
            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 435, GroupLayout.PREFERRED_SIZE).addComponent(jLabel2).addGroup(layout.createSequentialGroup().addGap(268, 268, 268).addComponent(jLabel1))).addGap(0, 0, Short.MAX_VALUE)));
            layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(220, 220, 220).addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)).addComponent(jLabel2)).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(13, 13, 13).addComponent(jLabel1)).addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))));
            pack();
        } // </editor-fold>

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Welcome().setVisible(true);
                }
            });
        }
        // Variables declaration - do not modify
        private JButton jButton1;
        private JLabel jLabel1;
        private JLabel jLabel2;
        private JLabel jLabel3;
        private JLabel jLabel4;
        private JLabel jLabel5;
        // End of variables declaration
    }
}
